export const memberList = [
  {
    name: "문상원",
    position: "Backend Engineer",
    year: 18,
    github: "https://github.com/MoonSangWon",
    detail: "",
  },
  {
    name: "박영건",
    position: "Frontend Engineer",
    year: 18,
    github: "https://github.com/jadru",
    detail: "",
  },
  {
    name: "박성훈",
    position: "Backend Engineer",
    year: 18,
    github: "https://github.com/Hoon9901",
    detail: "",
  },
  {
    name: "최진서",
    position: "Frontend Engineer",
    year: 18,
    github: "https://github.com/Dark-jin",
    detail: "",
  },
  {
    name: "신종웅",
    position: "Frontend Engineer",
    year: 21,
    github: "https://github.com/ShinJongUng",
    detail: "",
  },
  {
    name: "성병석",
    position: "Backend Engineer",
    year: 18,
    github: "https://github.com/sbs1621",
    detail: "",
  },
  {
    name: "문준호",
    position: "Backend Engineer",
    year: 19,
    github: "https://github.com/mjh000526",
    detail: "",
  },
  {
    name: "임채성",
    position: "Backend Engineer",
    year: 22,
    github: "https://github.com/puleugo",
    detail: "",
  },
  {
    name: "최경영",
    position: "Backend Engineer",
    year: 19,
    github: "https://github.com/KyeongYeongDEV",
    detail: "",
  },
  {
    name: "이성현",
    position: "Backend Engineer",
    year: 19,
    github: "https://github.com/sleeg00",
    detail: "",
  },
  {
    name: "이나린",
    position: "Frontend Engineer",
    year: 20,
    github: "https://github.com/narinn-star",
    detail: "",
  },
  {
    name: "문보경",
    position: "Frontend Engineer",
    year: 22,
    github: "https://github.com/qhrud00",
    detail: "",
  },
];
