export const Sessions = [
  {
    name: "박영건",
    info: "컴퓨터공학부 18 | 메가브레인",
    link: "https://www.github.com/jadru",
    title: "MEGACON 2022 인트로",
    type: "Keynote",
  },
  {
    name: "박성훈",
    info: "컴퓨터공학부 18 | 메가브레인",
    link: "https://www.github.com/Hoon9901",
    title: "메가브레인의 과거, 현재, 그리고 미래 시스템",
    type: "Keynote",
  },
  {
    name: "이성현",
    info: "컴퓨터공학부 18 | 메가브레인",
    link: "https://www.github.com/sleeg00",
    title: "Spring을 기초로 Redis 이해하기",
    type: "Backend",
  },
  {
    name: "이나린",
    info: "컴퓨터공학부 20 | 메가브레인",
    link: "https://www.github.com/narinn-star",
    title: "React Custom Hook 제작기",
    type: "Frontend",
  },
  {
    name: "문상원",
    info: "컴퓨터공학부 18 | 메가브레인",
    link: "https://www.github.com/Moonsangwon",
    title: "Spring에 InfluxDB 도입기",
    type: "Backend",
  },
  {
    name: "최진서",
    info: "컴퓨터공학부 18 | 메가브레인",
    link: "https://www.github.com/Dark-jin",
    title: "React 대시보드 제작기",
    type: "Frontend",
  },
  {
    name: "신종웅",
    info: "컴퓨터공학과 21 | 메가브레인",
    link: "https://www.github.com/ShinJongUng",
    title: "나의 DND 기록 - React Native, 협업, ...",
    type: "Dev. Log",
  },
  {
    type: "break",
  },
  {
    name: "박성훈",
    info: "컴퓨터공학부 18 | 메가브레인",
    link: "https://www.github.com/Hoon9901",
    title: "Spring Security 인증과 인가",
    type: "Backend",
  },
  {
    name: "박영건",
    info: "컴퓨터공학부 18 | 메가브레인",
    link: "https://www.github.com/jadru",
    title: "React 대시보드를 위한 디자인 시스템 설계",
    type: "Frontend",
  },
  {
    name: "문준호",
    info: "컴퓨터공학부 19 | 메가브레인",
    link: "https://www.github.com/mjh000526",
    title: "SSO와 Keycloak 인증",
    type: "Backend",
  },
  {
    name: "이병진",
    info: "컴퓨터공학부 20 | 메가브레인",
    link: "https://www.github.com/ByungJin-Lee",
    title: "React Library 사용이 꼭 올바른가?",
    type: "Frontend",
  },
  {
    name: "홍지현",
    info: "컴퓨터공학부 19 | 돗가비",
    link: "https://www.github.com/Hong-Study",
    title: "대규모 온라인 서버 - IOCP",
    type: "Backend",
  },
  {
    name: "성병석",
    info: "컴퓨터공학부 18 | 메가브레인",
    link: "https://www.github.com/sbs1621",
    title: "MQTT를 이용한 IoT 통신",
    type: "IoT",
  },

  {
    name: "임채성",
    info: "컴퓨터공학과 22 | 메가브레인",
    link: "https://www.github.com/puleugo",
    title: "소프트웨어 마에스트로: 리서치부터 앱 출시까지",
    type: "Dev. Log",
  },
];
