  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    # build job 완료 후 진행
    needs: Docker

    steps:
      - name: Get verion
        id: image
        run: |
          VERSION=$(echo ${{ github.sha }} | cut -c1-8)
          echo VERSION=$VERSION
          echo "::set-output name=version::$VERSION"
      
      # kustomize 명령을 가져온다.
      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1

      - name: Checkout kustomize repository
        uses: actions/checkout@v2
        with:
          # kubernetes 설정정보 저장소
          repository: inje-megabrain/Mega-Kubernetes
          ref: dev
          # 다른 저장소에 push 하려면 Personal Access Token이 필요.
          token: ${{ secrets.ACTION_TOKEN }}
          path: Mega-Kubernetes
          
      # 새 이미지 버전으로 파일 수정
      - name: Update Kubernetes resources
        run: |
          cd Mega-Kubernetes/mega-website/
          kustomize edit set image jadru/megabrain-website:${{ steps.image.outputs.version }}
          cat kustomization.yaml
          
      # 수정된 파일 commit & push
      - name: Commit files
        run: |
          cd Mega-Kubernetes
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git commit -am "Update image tag"
          git push -u origin deploy-argo
